In [139]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [140]:
df = sns.load_dataset('penguins')
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [142]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [143]:
column = ['bill_length_mm','bill_depth_mm','flipper_length_mm','body_mass_g']
for col in column:
  mean_value = df[col].mean()
  df[col] = df[col].fillna(mean_value)

In [144]:
df.isnull().sum()

species               0
island                0
bill_length_mm        0
bill_depth_mm         0
flipper_length_mm     0
body_mass_g           0
sex                  11
dtype: int64

In [145]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,Male
1,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,Female
2,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,Female
3,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,NaN
4,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,Female

In [146]:
df['sex'].isnull().sum()

np.int64(11)

In [147]:
mode_value = df['sex'].mode()[0]
df['sex'] = df['sex'].fillna(mode_value)
# mode_value

In [148]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [149]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,Male
1,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,Female
2,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,Female
3,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,Male
4,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,Female

In [150]:
df['sex'] = df['sex'].map({'Male':1,'Female':0})

In [151]:
df['island'].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

In [152]:
df = pd.get_dummies(df, columns=['island'], drop_first=True ,dtype=int)

In [153]:
df.head()

,species,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,island_Dream,island_Torgersen
0,Adelie,39.10000,18.70000,181.000000,3750.000000,1,0,1
1,Adelie,39.50000,17.40000,186.000000,3800.000000,0,0,1
2,Adelie,40.30000,18.00000,195.000000,3250.000000,0,0,1
3,Adelie,43.92193,17.15117,200.915205,4201.754386,1,0,1
4,Adelie,36.70000,19.30000,193.000000,3450.000000,0,0,1

In [154]:
x = df.drop(['species'],axis=1)
y = df['species']

In [155]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [156]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [157]:
from sklearn.linear_model import LogisticRegression

model_lo = LogisticRegression()
model_lo.fit(x_train_scaled, y_train)

LogisticRegression()

In [158]:
y_pred_lo = model_lo.predict(x_test_scaled)
y_pred_lo

array(['Chinstrap', 'Chinstrap', 'Gentoo', 'Chinstrap', 'Gentoo',
       'Gentoo', 'Gentoo', 'Gentoo', 'Adelie', 'Gentoo', 'Gentoo',
       'Adelie', 'Adelie', 'Adelie', 'Gentoo', 'Adelie', 'Adelie',
       'Gentoo', 'Gentoo', 'Adelie', 'Adelie', 'Adelie', 'Gentoo',
       'Adelie', 'Chinstrap', 'Chinstrap', 'Adelie', 'Chinstrap',
       'Adelie', 'Chinstrap', 'Adelie', 'Adelie', 'Chinstrap', 'Adelie',
       'Adelie', 'Adelie', 'Gentoo', 'Chinstrap', 'Adelie', 'Chinstrap',
       'Gentoo', 'Gentoo', 'Gentoo', 'Adelie', 'Adelie', 'Adelie',
       'Gentoo', 'Adelie', 'Adelie', 'Chinstrap', 'Adelie', 'Gentoo',
       'Gentoo', 'Adelie', 'Adelie', 'Chinstrap', 'Adelie', 'Chinstrap',
       'Chinstrap', 'Gentoo', 'Chinstrap', 'Adelie', 'Gentoo', 'Adelie',
       'Gentoo', 'Chinstrap', 'Adelie', 'Adelie', 'Adelie'], dtype=object)

In [159]:
y_test

194    Chinstrap
157    Chinstrap
225       Gentoo
208    Chinstrap
318       Gentoo
         ...
321       Gentoo
172    Chinstrap
73        Adelie
76        Adelie
16        Adelie
Name: species, Length: 69, dtype: object

In [160]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_pred_lo, y_test)

1.0

In [161]:
print("Confusion Matrix: \n", confusion_matrix(y_pred_lo,y_test))
print("\nClassification Report: \n", classification_report(y_pred_lo, y_test))

Confusion Matrix:
 [[32  0  0]
 [ 0 16  0]
 [ 0  0 21]]

Classification Report:
               precision    recall  f1-score   support

      Adelie       1.00      1.00      1.00        32
   Chinstrap       1.00      1.00      1.00        16
      Gentoo       1.00      1.00      1.00        21

    accuracy                           1.00        69
   macro avg       1.00      1.00      1.00        69
weighted avg       1.00      1.00      1.00        69

In [167]:
import numpy as np

def check_is_penguins():
  print("--------------------Check Is Penguin Species--------------------")

  try:
    bill_length_mm = float(input('Enter penguin bill length in (mm): '))
    bill_depth_mm = float(input('Enter penguin bill depth in (mm): '))
    flipper_length_mm = float(input('Enter penguin flipper length in (mm): '))
    body_mass_g = float(input('Enter penguin body mass in (g): '))
    sex_input = input('Enter sex(Male/Female): ').lower()
    island_input = input("Enter island(Dream, Torgersen, Biscoe): ").lower()
  except ValueError:
    print("\nInvalid input. Please enter appropriate values.")
    return

  #prepare features
  sex = 1 if sex_input == 'male' else 0
  island_Dream = 1 if island_input == 'dream' else 0
  island_Torgersen = 1 if island_input == 'torgersen' else 0

  feature_df = pd.DataFrame([[
      bill_length_mm,
      bill_depth_mm,
      flipper_length_mm,
      body_mass_g,
      sex,
      island_Dream,
      island_Torgersen
  ]], columns=x_train.columns) #Use x_train.columns to ensure order is correct

  scaled_feature = scaler.transform(feature_df)

  predicted_species = model_lo.predict(scaled_feature)
  prediction_proba = model_lo.predict_proba(scaled_feature)


  print("\n----------------------------------")
  print(f"Predicted Penguin Species: {predicted_species[0]}")
  print(f"Confidence: {np.max(prediction_proba) * 100:.2f}%")
  print("----------------------------------")

check_is_penguins()

--------------------Check Is Penguin Species--------------------
Enter penguin bill length in (mm): 56
Enter penguin bill depth in (mm): 16.8
Enter penguin flipper length in (mm): 180.1
Enter penguin body mass in (g): 4400.75
Enter sex(Male/Female): female
Enter island(Dream, Torgersen, Biscoe): biscoe

----------------------------------
Predicted Penguin Species: Chinstrap
Confidence: 87.27%
----------------------------------

In [166]:
df.tail()

,species,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,island_Dream,island_Torgersen
339,Gentoo,43.92193,17.15117,200.915205,4201.754386,1,0,0
340,Gentoo,46.80000,14.30000,215.000000,4850.000000,0,0,0
341,Gentoo,50.40000,15.70000,222.000000,5750.000000,1,0,0
342,Gentoo,45.20000,14.80000,212.000000,5200.000000,0,0,0
343,Gentoo,49.90000,16.10000,213.000000,5400.000000,1,0,0

In [164]:
df.describe()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,island_Dream,island_Torgersen
count,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000,344.000000
mean,43.921930,17.151170,200.915205,4201.754386,0.520349,0.360465,0.151163
std,5.443643,1.969027,14.020657,799.613058,0.500313,0.480835,0.358729
min,32.100000,13.100000,172.000000,2700.000000,0.000000,0.000000,0.000000
25%,39.275000,15.600000,190.000000,3550.000000,0.000000,0.000000,0.000000
50%,44.250000,17.300000,197.000000,4050.000000,1.000000,0.000000,0.000000
75%,48.500000,18.700000,213.000000,4750.000000,1.000000,1.000000,0.000000
max,59.600000,21.500000,231.000000,6300.000000,1.000000,1.000000,1.000000

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64